### PR TITLE
Improve VR controller

### PR DESCRIPTION
**Pull request by microchipgnu**
After experimenting with SpacesVR and playing around with some websites like https://muse.place, I noticed the VR controllers weren't working as expected. 

Some of the issues I found (video below): 
- Controllers didn't "follow" the user. 
- Smooth Turn is known for causing motion sickness. Snap Turn is a better default option.

https://user-images.githubusercontent.com/5553483/123548746-06728c00-d75e-11eb-8564-d525394e696e.mp4

I took a stab at it and what I thought would be a quick fix, made me change a few more things. Would like some general feedback, but specifically L102-L106, since I tried to maintain the current [Player](https://github.com/spacesvr/spacesvr/blob/master/src/core/players/Player.tsx) implementation but might be missing something here. I'm unsure what the `direction` should be in this case.

https://user-images.githubusercontent.com/5553483/123548969-edb6a600-d75e-11eb-8f13-fecb3498cfb1.mp4

### CODE REVIEW

**Comment by microchipgnu** [comment]
Hey, any feedback?

**Comment by alex-shortt** [comment]
sorry for the delay, been caught up making a platform for all this that i'll be sure to share with you :)
I'll look into it today!

**Review by alex-shortt — APPROVED** [review]
looks good! wasn't able to test it but the code looks good so i'll try debugging on my vercel links on dev

**Comment by microchipgnu** [comment]
I know it's already closed! Thanks! 

Don't mind improving the controllers too if any issues arise :)

I'll be keeping an eye out

**Pull request merged**
