### PR TITLE
adjustable player height functionality

### PR DESCRIPTION
**Pull request by ianyimi**
slightly tweaked player collider w a different function

### CODE REVIEW

**Comment by alex-shortt** [comment]
hey sorry just seeing this .. honestly not too sure how i feel about letting users adjust height. it would bring up some bad accessibility issues with trying to navigate between worlds that are meant to be experienced at different heights. and honestly, don't really see the upside. why not just scale the content to fit the given player height?

only avenue i could see this working through is dynamic changes in player height, which could allow for hidden content via scale (thinking along the lines of a bedroom with a desk, where when scaled down the desk is its own "page").

**Comment by ianyimi** [comment]
> hey sorry just seeing this .. honestly not too sure how i feel about letting users adjust height. it would bring up some bad accessibility issues with trying to navigate between worlds that are meant to be experienced at different heights. and honestly, don't really see the upside. why not just scale the content to fit the given player height?
> 
> only avenue i could see this working through is dynamic changes in player height, which could allow for hidden content via scale (thinking along the lines of a bedroom with a desk, where when scaled down the desk is its own "page").

No worries no worries. I did this because in a couple of my sites I felt like I had everything scaled but just wanted the player to be taller in the scene. Sometimes if I scaled it down for the player to be the correct height then everything else looked too small. 
https://etherrealms-dyq76htzz-ianyimi.vercel.app/
for this one the player was extremely short and on the ground, so I raised the floor collider up one to be floating in the air. I just wanted to add this functionality so I could keep my collisions consistent And I'm only going to use it to make my player a height of 2 instead of 1. I could restrict it to these two values instead. I could also still probably get it to work by scaling everything else but it was faster for me to change the player height

**Comment by alex-shortt** [comment]
> I could also still probably get it to work by scaling everything else but it was faster for me to change the player height

Yeah this is 100% what you have to be aware of from the start, that's just a part of 3d design.

To highlight the issue, I'm aware of a bug with the vr player's height being too high. I haven't had time to find the bug, but i'm pretty sure it uses the meters to scale the player, which the average height is ~1.7m. However, we scaled the player to 1m, so you are extra tall in vr compared to mobile/desktop. Now, I have two choices: re-scale every single template and idea that exists in the muse worlds and get all spacesvr users to re-scale their worlds to match the new height, or scale down the vr player height to the standardized 1m. 

It's sort of a separate issue, but hopefully you can see how important the player height is. And the issue would only compound if everyone could set their own player height.

**Comment by alex-shortt** [comment]
going to close this for now, happy to open up a discussion if you want to talk about a way to dynamically change height, but i don't see a good argument for setting player height.

**Pull request closed without merging**
